#!/usr/bin/env bash
set -euo pipefail

usage() {
    cat <<'EOF'
Usage: render-gateway-config.sh \
  --output-dir DIR \
  --server-private-key-file FILE \
  --client-public-key KEY \
  --external-interface NAME \
  [--vpn-port PORT] \
  [--server-address CIDR] \
  [--client-address CIDR]
EOF
}

die() {
    printf 'Error: %s\n' "$1" >&2
    exit 1
}

valid_wireguard_key() {
    [[ "$1" =~ ^[A-Za-z0-9+/]{43}=$ ]]
}

valid_ipv4_cidr() {
    local value="$1"
    local address prefix octet
    [[ "$value" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}/([0-9]|[12][0-9]|3[0-2])$ ]] || return 1
    address="${value%/*}"
    prefix="${value#*/}"
    [[ "$prefix" -ge 0 && "$prefix" -le 32 ]] || return 1
    IFS='.' read -r -a octets <<< "$address"
    for octet in "${octets[@]}"; do
        [[ "$octet" =~ ^(0|[1-9][0-9]{0,2})$ ]] || return 1
        (( 10#$octet >= 0 && 10#$octet <= 255 )) || return 1
    done
}

output_dir=''
server_private_key_file=''
client_public_key=''
external_interface=''
vpn_port='51820'
server_address='10.88.0.1/24'
client_address='10.88.0.2/32'

while [[ $# -gt 0 ]]; do
    case "$1" in
        --output-dir) output_dir="${2-}"; shift 2 ;;
        --server-private-key-file) server_private_key_file="${2-}"; shift 2 ;;
        --client-public-key) client_public_key="${2-}"; shift 2 ;;
        --external-interface) external_interface="${2-}"; shift 2 ;;
        --vpn-port) vpn_port="${2-}"; shift 2 ;;
        --server-address) server_address="${2-}"; shift 2 ;;
        --client-address) client_address="${2-}"; shift 2 ;;
        --help|-h) usage; exit 0 ;;
        *) die "Unknown argument: $1" ;;
    esac
done

[[ -n "$output_dir" ]] || die '--output-dir is required.'
[[ -f "$server_private_key_file" ]] || die 'The server private key file does not exist.'
[[ -n "$client_public_key" ]] || die '--client-public-key is required.'
[[ "$external_interface" =~ ^[A-Za-z0-9_.:-]{1,15}$ ]] || die 'The external interface name is invalid.'
[[ "$vpn_port" =~ ^[0-9]+$ ]] && [[ "$vpn_port" -ge 1 && "$vpn_port" -le 65535 ]] || die 'The VPN port must be between 1 and 65535.'
valid_ipv4_cidr "$server_address" || die 'The server address must be an IPv4 CIDR address.'
valid_ipv4_cidr "$client_address" || die 'The client address must be an IPv4 CIDR address.'

server_private_key="$(cat -- "$server_private_key_file")"
valid_wireguard_key "$server_private_key" || die 'The server private key file is not a WireGuard key.'
valid_wireguard_key "$client_public_key" || die 'The client public key is not a WireGuard key.'

vpn_network="${server_address%.*}.0/${server_address#*/}"
if [[ "${server_address#*/}" != '24' ]]; then
    die 'The bootstrap renderer currently requires a /24 server network.'
fi

temporary_dir="$(mktemp -d)"
trap 'rm -rf -- "$temporary_dir"' EXIT

cat > "$temporary_dir/wg-maplebridge.conf" <<EOF
# Generated by MapleBridge. Contains a private key; do not commit or share.
[Interface]
Address = $server_address
ListenPort = $vpn_port
PrivateKey = $server_private_key

[Peer]
PublicKey = $client_public_key
AllowedIPs = $client_address
EOF

cat > "$temporary_dir/maplebridge.nft" <<EOF
#!/usr/sbin/nft -f

define wan_if = "$external_interface"
define wg_if = "wg-maplebridge"
define vpn_port = $vpn_port
define vpn_net = $vpn_network

table inet maplebridge_filter {
    chain input {
        type filter hook input priority filter; policy drop;
        ct state invalid drop
        ct state established,related accept
        iifname "lo" accept
        ip protocol icmp accept
        meta l4proto ipv6-icmp accept
        udp sport 67 udp dport 68 accept
        udp dport \$vpn_port accept
    }

    chain forward {
        type filter hook forward priority filter; policy drop;
        ct state invalid drop
        ct state established,related accept
        iifname \$wg_if oifname \$wan_if accept
    }

    chain output {
        type filter hook output priority filter; policy accept;
    }
}

table ip maplebridge_nat {
    chain postrouting {
        type nat hook postrouting priority srcnat; policy accept;
        ip saddr \$vpn_net oifname \$wan_if masquerade
    }
}
EOF

cat > "$temporary_dir/99-maplebridge-forward.conf" <<'EOF'
# Generated by MapleBridge.
net.ipv4.ip_forward = 1
EOF

cat > "$temporary_dir/maplebridge-firewall.service" <<'EOF'
[Unit]
Description=MapleBridge nftables rules
After=network-pre.target
Before=network.target wg-quick@wg-maplebridge.service
Wants=network-pre.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStartPre=-/usr/sbin/nft delete table inet maplebridge_filter
ExecStartPre=-/usr/sbin/nft delete table ip maplebridge_nat
ExecStart=/usr/sbin/nft -f /etc/maplebridge/maplebridge.nft
ExecStop=-/usr/sbin/nft delete table inet maplebridge_filter
ExecStop=-/usr/sbin/nft delete table ip maplebridge_nat

[Install]
WantedBy=multi-user.target
EOF

mkdir -p -- "$output_dir"
install -m 0600 "$temporary_dir/wg-maplebridge.conf" "$output_dir/wg-maplebridge.conf"
install -m 0600 "$temporary_dir/maplebridge.nft" "$output_dir/maplebridge.nft"
install -m 0644 "$temporary_dir/99-maplebridge-forward.conf" "$output_dir/99-maplebridge-forward.conf"
install -m 0644 "$temporary_dir/maplebridge-firewall.service" "$output_dir/maplebridge-firewall.service"
